// Generated by CoffeeScript 1.6.3
(function() {
  var createCanvas, crop, repeat, scale;

  createCanvas = function(w, h) {
    var canvas, context;
    canvas = document.createElement('canvas');
    canvas.setAttribute('width', w);
    canvas.setAttribute('height', h);
    context = canvas.getContext('2d');
    return [canvas, context];
  };

  repeat = function(sourceImage, timesX, timesY) {
    var canvas, context, destH, destW, pattern, _ref;
    destW = sourceImage.width * timesX;
    destH = sourceImage.height * timesY;
    _ref = createCanvas(destW, destH), canvas = _ref[0], context = _ref[1];
    pattern = context.createPattern(sourceImage, 'repeat');
    context.fillStyle = pattern;
    context.fillRect(0, 0, destW, destH);
    return canvas.toDataURL();
  };

  scale = function(sourceImage, scaleX, scaleY) {
    var canvas, context, destH, destW, _ref;
    destW = sourceImage.width * scaleX;
    destH = sourceImage.width * scaleY;
    _ref = createCanvas(destW, destH), canvas = _ref[0], context = _ref[1];
    context.drawImage(sourceImage, 0, 0, destW, destH);
    return canvas.toDataURL();
  };

  crop = function(sourceImage, ox, oy, ow, oh) {
    var canvas, context, destH, destW, sh, sw, sx, sy, _ref;
    sx = ox || 0;
    sy = oy || 0;
    destW = sourceImage.width - (ow || 0) - sx;
    destH = sourceImage.height - (oh || 0) - sy;
    sw = destW;
    sh = destH;
    _ref = createCanvas(destW, destH), canvas = _ref[0], context = _ref[1];
    console.log(sx, sy, sw, sh, 0, 0, destW, destH);
    context.drawImage(sourceImage, sx, sy, sw, sh, 0, 0, destW, destH);
    return canvas.toDataURL();
  };

  module.exports = {
    repeat: repeat,
    scale: scale,
    crop: crop
  };

}).call(this);
